#!/bin/sh

set -e

if [ "$1" = "purge" ] || [ "$1" = "remove" ]
then
	if [ -x "$(which update-gsfontmap 2>/dev/null)" ]
	then
		update-gsfontmap
	fi
fi

if [ "$1" = "purge" ]
then
	if ! [ -x "$(which update-fonts-dir 2>/dev/null)" ]
	then
		rm -f /usr/share/fonts/X11/Type1/fonts.alias
		rm -f /usr/share/fonts/X11/Type1/fonts.dir
		rm -f /usr/share/fonts/X11/fonts.scale
	fi
fi

#DEBHELPER#

exit 0
